### PR TITLE
Add example database, updated readme, added delete_post.php.

### PR DESCRIPTION
**Pull request by Pinball3D**
I added an example database with chirps, users, following, likes, reposts, and replies tables. Some of the column definitions may not be correct but everything works fine to post with this database. I updated the readme with instructions on how to use the database. A post request to delete_post.php with ?chirp=<id> will replace the chirp content with "This chirp is not available." There is also code that would fully remove the post.

@smileyzone on chirp

### CODE REVIEW

**Comment by actuallyaridan** [comment]
delete_chirp.php should *not* work like that.

**Comment by Pinball3D** [comment]
> delete_chirp.php should *not* work like that. 

How should it work?

**Comment by actuallyaridan** [comment]
It should remove the posts entry from the database, remove the likes along with rechirps associated with it. 
Probably smarter if I add it.

**Comment by Pinball3D** [comment]
> It should remove the posts entry from the database, remove the likes along with rechirps associated with it. 
> 
> Probably smarter if I add it. 

Ok, can you add the database file at least?

**Comment by actuallyaridan** [comment]
Should be added now.

**Pull request closed without merging**
