### PR TITLE
Traslate to pl-PL

### PR DESCRIPTION
**Pull request by parpok**
POLSKA GUROM I guess LOL
https://youtu.be/wGeFVtLo1RA?si=KPHSfqA_cEY1YmqL

### CODE REVIEW

**Comment by actuallyaridan** [comment]
You seem to have the wrong version number, and   "en-US": "Polski ", should be "pl-PL:" "Polski (Polish)"

**Comment by actuallyaridan** [comment]
you seem to also miss a lot of translations :p

**Comment by parpok** [comment]
Changed this    "pl-PL": "Polski",
Also I haven't bothered with the comments
Are they going to be shown or are they just for help

**Comment by actuallyaridan** [comment]
comments are so you translate it properly. they’re not shown and do not need to be translated.

stuff still looks off though. Are you using the latest version of en-US as a base?

**Comment by actuallyaridan** [comment]
your repo is multiple commits behind, sync it first, then translate it lol

**Comment by actuallyaridan** [comment]
yuh thnx

**Pull request merged**
